# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Server Code
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./server/package-lock.json

    - name: Install Server Dependencies
      run: |
          cd ./server
          npm ci

    - name: Start server
      run: |
          cd ./server
          npm start
          
    - name: Deploy Client Files
      uses: appleboy/scp-action@master
      with:
        host: 3.16.187.217
        username: ec2-user
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        source: client/
        target: /var/www/html/
